#9 Feature: Create roles and set permissions
atlp-rwanda/phantom-be-elite pull request #17
Opened 2022-06-22 13:55 UTC by benshyaka

#### What does this PR do?

As an admin, 
- will create roles and set its permissions

#### Description of Task to be completed?

- The admin should be able to assign roles to users.
- the admin should be able to assign persmissions to its correspond roles

#### How should this be manually tested?

- Clone the repo
- checkout to branch `ft-create-roles-9`
- pull the changes by `git pull`
- install all packages by running `npm i`
- start the app by running `npm run start:dev`

**In your API testing tool (postman recommended) call API** 

- `method: Get` `http://localhost:3001/api/v1/roles/:{id}` to fetch userdata
- `method: Put` `http://localhost:3001/api/v1/roles/update/:{id}` to assign role to the user

#### Any background context you want to provide?

- You need to be logged in to perform an admin operation 
- `method: Post` `http://localhost:3000/api/v1/auth/login` to fetch user data

 {
  "email":"admin@gmail.com",
  "password":"password"
}

- Copy the returned jwt token from returned JSON and create a new header called token and pass the value

- **Assigning a new role to a user pass JSON with role and user id** 
 ```js script
  {
    "role": "operator",
    "id": "2"
  }
  ```

#### What are the relevant Pivotal Tracker/Trello stories?

https://trello.com/c/YcFd9M8O/9-create-roles-and-set-permissions

#### Screenshots (if appropriate)

-  N/A

#### Questions:

-  N/A

2022-06-24 09:16 UTC, PrinceNiyonshuti approved these changes
looks good to me

2022-06-24 09:31 UTC, Xldivin approved these changes

2022-06-26 21:48 UTC, PatrickNiyogitare28 requested changes
Add translations and resolve the conflicts

2022-06-27 07:19 UTC, tysepa approved these changes

2022-06-28 15:15 UTC, PatrickNiyogitare28 approved these changes

2022-06-29 10:48 UTC, Salim-54 approved these changes

2022-06-29 11:00 UTC, Hodal66 approved these changes

2022-06-29 17:53 UTC, merged