#19 Chore: setup docker
atlp-rwanda/phantom-be-elite pull request #8
Opened 2022-06-14 19:46 UTC by Niyonkuru1

### What does this PR do?
Add the docker config file for creating images of the application. This will be done at the end of the project, at least three images will be created and communication will be established between them.
### Description of Task to be completed?
- To create an image of backend
- To configure and run database in a docker container
- Both docker images can communicate while up and running
### How should this be manually tested?
`Docker` should be `installed` in your pc and configured to create and run images

`Clone the repo`

`checkout` to branch `ch-setup-docker-19
`

pull the changes by `git pull`

After checking that docker app is already installed,  Run `docker-compose up -d` to create an image from the docker-compose file and create container.

Then go to the browser and you should see the message being rendered. `IT IS NO MORE NECESSARY TO START SERVER LOCALLY`, docker handles them in the container

### Any background context you want to provide?
N/A

### What are the relevant pivotal tracker stories?
[Trello Board](https://trello.com/c/6CnMHtYC/19-setup-docker)

Screenshots (if appropriate)

[WIP #19]

2022-06-14 19:56 UTC, PatrickNiyogitare28 requested changes
Rebase to remove the conflicts

2022-06-15 00:18 UTC, Niyonkuru1 commented
> Rebase to remove the conflicts

Yes I have did them. thank you

2022-06-15 09:53 UTC, mukunzidd approved these changes
``

2022-06-15 10:01 UTC, Xldivin approved these changes

2022-06-15 10:06 UTC, PatrickNiyogitare28 approved these changes

2022-06-15 10:06 UTC, merged